name: IA-For-PAF
version: ${project.version}
author: Simonsator
depends: [ PartyAndFriends ]
depend: [ PartyAndFriends ]
main: de.simonsator.partyandfriends.interactall.IAMain
description: An add-on for Party and Friends which adds the commands /friend acceptall and /friend denyall
api-version: 1.13