name: IA-For-PAF
version: ${project.version}
author: Simonsator
depends: [PartyAndFriends]
depend: [PartyAndFriends]
main: de.simonsator.partyandfriends.interactall.IAMain
description: An add-on for party and friends to add /friend acceptall and /friend denyall